ingress:
  - hostname: api.self-link.com
    path: /api/v1/community/*
    service: http://asgi:8001

  - hostname: api.self-link.com
    path: /ws*
    service: http://realtime:8001
  - hostname: api.self-link.com
    path: /api/v1/mentor/stream*
    service: http://asgi:8001
  - hostname: api.self-link.com
    path: /media/*
    service: http://media:8080
  - hostname: api.self-link.com
    path: /api*
    service: http://asgi:8001
  - hostname: api.self-link.com
    service: http://asgi:8001
  - service: http_status:404
