tunnel: <TUNNEL_UUID>
credentials-file: /etc/cloudflared/<TUNNEL_UUID>.json

ingress:
  - hostname: api.self-link.com
    path: /api/v1/community/*
    service: http://localhost:8001
    originRequest:
      noTLSVerify: true

  - hostname: api.self-link.com
    path: /ws*
    service: http://localhost:8002
    originRequest:
      noTLSVerify: true
  - hostname: api.self-link.com
    path: /api/v1/mentor/stream*
    service: http://localhost:8001
    originRequest:
      noTLSVerify: true
  - hostname: api.self-link.com
    path: /media/*
    service: http://localhost:8080
    originRequest:
      noTLSVerify: true
  - hostname: api.self-link.com
    path: /api*
    service: http://localhost:8001
    originRequest:
      noTLSVerify: true
  - hostname: api.self-link.com
    service: http://localhost:8001
    originRequest:
      noTLSVerify: true
  - service: http_status:404
